version: "3"
services:

  screenly-ose-server:
    container_name: "screenly-ose-server"
    build: .
    image: screenly-ose-server
    network_mode: "host"
    privileged: true
    environment:
      - LISTEN=raspberrypi 
      - PORT=8080
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /home/pi/screenly:/home/pi/screenly
      - /home/pi/.screenly:/home/pi/.screenly
      - /home/pi/screenly_assets:/home/pi/screenly_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  screenly-ose-viewer:
    container_name: "screenly-ose-viewer"
    build: .
    image: screenly-ose-viewer
    depends_on:
      - screenly-ose-server
      - screenly-ose-websocket
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    volumes:
      - /home/pi/screenly:/home/pi/screenly
      - /home/pi/.screenly:/home/pi/.screenly
      - /home/pi/screenly_assets:/home/pi/screenly_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  screenly-ose-websocket:
    container_name: "screenly-ose-websocket"
    build: .
    image: screenly-ose-websocket
    depends_on: 
      - screenly-ose-server
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    volumes:
      - /home/pi/screenly:/home/pi/screenly
      - /home/pi/.screenly:/home/pi/.screenly
      - /home/pi/screenly_assets:/home/pi/screenly_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
